FROM adoptopenjdk/openjdk11

MAINTAINER Fabian Perez <fperezv@payqa.dev>

ADD payqa-ulikme-ws-meet-api/target/payqa-ulikme-ws-meet.jar payqa-ulikme-ws-meet.jar

ENTRYPOINT ["java", "-jar", "payqa-ulikme-ws-meet.jar"]