FROM adoptopenjdk/openjdk11

MAINTAINER Fabian Perez <fperezv@payqa.dev>

ADD payqa-ulikme-ws-establishment-api/target/payqa-ulikme-ws-establishment.jar payqa-ulikme-ws-establishment.jar

ENTRYPOINT ["java", "-jar", "payqa-ulikme-ws-establishment.jar"]