FROM adoptopenjdk/openjdk11

MAINTAINER Fabian Perez <fperezv@payqa.dev>

ADD payqa-ulikme-ws-country-api/target/payqa-ulikme-ws-country.jar payqa-ulikme-ws-country.jar

ENTRYPOINT ["java", "-jar", "payqa-ulikme-ws-country.jar"]