FROM adoptopenjdk/openjdk11

MAINTAINER Fabian Perez <fperezv@payqa.dev>

ADD payqa-ulikme-ws-person-api/target/payqa-ulikme-ws-person.jar payqa-ulikme-ws-person.jar

ENTRYPOINT ["java", "-jar", "payqa-ulikme-ws-person.jar"]