auth0:
  domain: https://dev-n5d28qok.us.auth0.com #https://payqa-int.us.auth0.com/
  jwk-url: https://dev-n5d28qok.us.auth0.com #https://payqa-int.us.auth0.com/
  issuer: https://dev-n5d28qok.us.auth0.com #https://payqa-int.us.auth0.com/
firebase:
  service-account: firebase-dev-key.json
twilio:
  account-sid: ACad71967cf7ae4cfe51a16ecc1995e1c3
  auth-token: 2b2c206689eefd057475b948da60b21a
  enabled: true
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
  data:
    mongodb:
      authentication-database: admin
      uri: mongodb://localhost:27017
app:
  config:
    max-photos: 8