auth0:
  domain: https://dev-n5d28qok.us.auth0.com #https://payqa-int.us.auth0.com/
  jwk-url: https://dev-n5d28qok.us.auth0.com #https://payqa-int.us.auth0.com/
  issuer: https://dev-n5d28qok.us.auth0.com #https://payqa-int.us.auth0.com/
backend:
  person:
    url: http://localhost:8086/ #/payqa-ulikme-ws-person/
  establishment:
    url: http://localhost:8087/ #/payqa-ulikme-ws-establishment/
spring:
  data:
    mongodb:
      authentication-database: admin
      uri: mongodb+srv://ulikmeapp:iFkec9PXXhShOv24@ulikme.b5djnl2.mongodb.net/ulikme?retryWrites=true&w=majority
      database: ulikme
server:
  port : 8090