FROM adoptopenjdk/openjdk11

MAINTAINER Fabian Perez <fperezv@payqa.dev>

ADD target/payqa-ulikme-job-scheduler.jar payqa-ulikme-job-scheduler.jar

ENTRYPOINT ["java", "-jar", "payqa-ulikme-job-scheduler.jar"]