auth0:
  domain: https://dev-n5d28qok.us.auth0.com #https://payqa-int.us.auth0.com/
  jwk-url: https://dev-n5d28qok.us.auth0.com #https://payqa-int.us.auth0.com/
  issuer: https://dev-n5d28qok.us.auth0.com #https://payqa-int.us.auth0.com/
spring:
  data:
    mongodb:
      authentication-database: admin
      uri: mongodb://localhost:27017
      database: ulikme
server:
  port: 8082