FROM adoptopenjdk/openjdk11

MAINTAINER Fabian Perez <fperezv@payqa.dev>

ADD payqa-ulikme-ws-interest-api/target/payqa-ulikme-ws-interest.jar payqa-ulikme-ws-interest.jar

ENTRYPOINT ["java", "-jar", "payqa-ulikme-ws-interest.jar"]