FROM adoptopenjdk/openjdk11

MAINTAINER Fabian Perez <fperezv@payqa.dev>

ADD payqa-ulikme-ws-chat-api/target/payqa-ulikme-ws-chat.jar payqa-ulikme-ws-chat.jar

ENTRYPOINT ["java", "-jar", "payqa-ulikme-ws-chat.jar"]