FROM adoptopenjdk/openjdk11

MAINTAINER Fabian Perez <fperezv@payqa.dev>

ADD payqa-ulikme-ws-interaction-api/target/payqa-ulikme-ws-interaction.jar payqa-ulikme-ws-interaction.jar

ENTRYPOINT ["java", "-jar", "payqa-ulikme-ws-interaction.jar"]